spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jaydb
    username: root
    password: js365@dwy5

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true